version: "3.1"

services:
  kafka:
    image: apache/kafka:4.0.0
    restart: unless-stopped
    ports:
      - 9092:9092
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
